import TripPlannerForm from '@/components/TripPlannerForm';

export default function Home() {
  return (
    <main className="min-h-screen bg-gray-50 py-6">
      <div className="max-w-4xl mx-auto px-4">
        <h1 className="text-4xl font-bold text-center text-gray-900 mb-2">
          AI Trip Planner
        </h1>
        <p className="text-center text-gray-600">
          Get a personalized trip itinerary generated by AI based on your preferences
        </p>
        <TripPlannerForm />
      </div>
    </main>
  );
}
