import TripPlannerForm from '@/components/TripPlannerForm';
import HeroSection from '@/components/HeroSection';
import FeaturesSection from '@/components/FeaturesSection';

export default function Home() {
  return (
    <main className="min-h-screen bg-gray-50">
      <HeroSection />
      <FeaturesSection />
      <section id="planner" className="py-20 bg-gray-50">
        <div className="max-w-4xl mx-auto px-4">
          <h2 className="text-4xl font-bold text-center text-gray-900 mb-2">
            Plan Your Trip
          </h2>
          <p className="text-center text-gray-600 mb-8">
            Get a personalized trip itinerary generated by AI based on your preferences
          </p>
          <TripPlannerForm />
        </div>
      </section>
    </main>
  );
}
